/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfirmDialog: typeof import('./components/ConfirmDialog.vue')['default']
    FormDialog: typeof import('./components/FormDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusColumn: typeof import('./components/StatusColumn.vue')['default']
    TaskCard: typeof import('./components/TaskCard.vue')['default']
    TaskSearchFilters: typeof import('./components/TaskSearchFilters.vue')['default']
  }
}
